# 应用名称
app_name: herman
# 应用运行环境模式(debug/test/release)
mode: debug
# 时区
timezone: Asia/Shanghai
# 路由前缀
app_prefix: /api/v1
# 语言
language: zh-CN

# 数据库配置
mysql:
  # 连接IP地址
  host: 127.0.0.1
  # 连接端口号
  port: 3306
  # 连接用户名
  user: root
  # 连接密码
  password: root
  # 连接数据库名称
  dbname: herman
  # 最大连接数
  max_open_conn: 100
  # 最大连接空闲数，建议和max_open_conn一致
  max_idle_conn: 10

# Redis配置
redis:
  # 连接IP地址
  host: 127.0.0.1
  # 连接端口号
  port: 6379
  # 连接用户名
  username:
  # 连接密码
  password:
  # 默认数据库，默认是0
  db: 0
  # 最大连接数
  pool_size: 100

# Kafka配置
kafka:
  # 连接IP地址
  host: 127.0.0.1
  # 连接端口号
  port: 9092

# 日志配置
log:
  # 日志级别模式
  level: info
  # 日志文件名
  filename: herman.log
  # 单个日志文件大小(MB)，日志大小到达max_size就开始backup
  max_size: 200
  # 旧日志保存的最大天数，默认保存所有旧日志文件
  max_age: 90
  # 旧日志保存的最大数量，默认保存所有旧日志文件
  max_backups: 7
  # backup的日志是否使用本地时间戳，默认使用UTC时间
  local_time: true
  # 对backup的日志是否进行压缩，默认不压缩
  compress: true

# JWT配置
jwt:
  # token的SECRET 可以执行herman jwt:secret命令随机生成
  secret: M78ZSb4dDgdIj8GYLrFNDEi4Lh4bJtXzinlw2IVHgQY=
  # token有效时间（单位：小时）
  effect_time: 2

# 验证码配置
captcha:
  # 验证码开关
  switch: false
  # 水印
  text: 我的水印
  # 验证码类型驱动（本地内存：mem，Redis内存：redis）
  cache_type: redis
  # 缓存有效时间（单位：秒）
  cache_expire_sec: 120
  # 项目的绝对路径: 图片、字体等
  resource_path: ./

# 短信宝配置
sms:
  # 短信宝接口
  api: http://api.smsbao.com/
  # 短信宝用户名
  user:
  # 短信宝密码
  password:

# 文件存储驱动
storage:
  # 文件存储类型（本地：local，阿里云OSS：oss，七牛云：qiniu，腾讯云COS：cos）
  drive: local
    # 本地存储配置
    local:
      # 本地存储路径
      path: ./resources/files/uploads
    # 阿里云OSS配置
    oss:
      # 阿里云OSS的AccessKeyID
      access_key_id:
      # 阿里云OSS的AccessKeySecret
      access_key_secret:
      # 阿里云OSS的Bucket
      bucket:
      # 阿里云OSS的Endpoint
      endpoint:
      # 阿里云OSS的外网域名
      domain:
    # 七牛云配置
    qiniu:
      # 七牛云的AccessKey
      access_key:
      # 七牛云的SecretKey
      secret_key:
      # 七牛云的Bucket
      bucket:
      # 七牛云的外网域名
      domain:
      # 七牛云的Zone
      zone:
      # 七牛云的UseHTTPS
      use_https:
    # 腾讯云COS配置
    cos:
      # 腾讯云COS的AppID
      app_id:
      # 腾讯云COS的SecretID
      secret_id:
      # 腾讯云COS的SecretKey
      secret_key:
      # 腾讯云COS的Bucket
      bucket:
      # 腾讯云COS的Region
      region:
      # 腾讯云COS的外网域名
      domain:
      # 腾讯云COS的UseHTTPS
      use_https: