app_name: "fp-gin-framework"
version: "1.0.0"
app_prefix: "/api/v1"
mode: "test"
port: 7777

# 数据库配置
mysql:
  host: 204.44.94.254
  port: 3306
  user: "fp"
  password: "LXSGD6yAT6fHJHEw"
  dbname: "fp"
  prefix: "fp_"
  max_open_conn: 200
  max_ids_conn: 10

# Redis配置
redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 3
  pool_size: 100

# 日志配置
log:
  level: "debug"
  filename: "gin.log"
  max_size: 200
  max_age: 30
  max_backups: 7

# JWT配置
jwt:
  # token的SECRET
  jwt_secret: "coTnkidMZBSNdoQPStGYMlLndWym86c5b7LXhHd3RgFn44AY9a4ERZYQepBvHXAc"
  # token有效时间（单位：小时）
  effect_time: 2